version: '3.8'

services:
  db:
    image: mongo
    restart: always
    container_name: db
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/test
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - app-network
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_URL: mongodb://db:27017/test
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app-network
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge