version: '3.8'

services:
  db:
    image: mongo:8.0.0
    restart: always
    container_name: db
    networks:
      - app-network
    # Убрали строки с открытыми портами
    volumes:
      - mongo_data:/test

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - app-network
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_URL: mongodb://db:27017/test
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app-network
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge